# UAT Environment Values
# Overrides for the UAT environment

replicaCount: 1

image:
  pullPolicy: Always
  containerPort: 8000

ingress:
  enabled: true
  className: "modsec"
  annotations: {}
    # Dynamic annotations will be set by workflow for ephemeral deployments
  hosts:
    - host: laa-cla-operator-app-uat.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
  whitelist:
    enabled: true

resources: {}

# Environment variables can be added here
envVars: {}
