name: Feature Branch

run-name: Feature - ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - reopened

permissions: {}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    permissions: {}

  #   TODO: Re-enable this when we have tests with coverage reports to analyse
  #   name: Static Analysis
  #   needs: test
  #   uses: ./.github/workflows/static-analysis.yml
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  build-and-push:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      id-token: write
    with:
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}


    name: Snyk scan docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Get Snyk OAuth Token
        id: snyk-auth
        run: |
          TOKEN=$(curl -s -X POST "https://api.snyk.io/oauth2/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.SNYK_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.SNYK_CLIENT_SECRET }}" \
            | jq -r '.access_token')

          echo "SNYK_OAUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Build local Docker image
        run: |
          docker build \
            --tag laa-cla-operator-app:scan \
            --file Dockerfile .

      - name: Run Snyk to scan Docker image
        uses: snyk/actions/docker@c75628d834bd4a804426e1cb7b31a9aa43a54c31
        with:
          image: laa-cla-operator-app:scan
          args: --docker --severity-threshold=high --policy-path=.snyk
        env:
          SNYK_OAUTH_TOKEN: ${{ env.SNYK_OAUTH_TOKEN }}

  # snyk-auth:
  #   runs-on: ubuntu-latest
  #   needs: [build-and-push]
  #   outputs:
  #     snyk_token: ${{ steps.get_snyk_token.outputs.token }}
  #   steps:
  #     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
  #     - name: Get snyk token
  #       id: get_snyk_token
  #       uses: ministryofjustice/laa-reusable-github-actions/.github/actions/snyk-auth@main
  #       with:
  #         client_id: ${{ secrets.SNYK_CLIENT_ID }}
  #         client_secret: ${{ secrets.SNYK_CLIENT_SECRET }}
  #     - name: Validate Token Presence
  #       run: |
  #         if [ -z "${{ steps.get_snyk_token.outputs.token }}" ]; then
  #           echo "Token is empty!"
  #           exit 1
  #         fi

  # scan-image:
  #   needs: [build-and-push, snyk-auth]
  #   uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/snyk.yml@main
  #   with:
  #     tag: snyk-scan
  #     dockerfile_path: "Dockerfile"
  #   secrets:
  #     snyk_token: ${{ secrets.SNYK_OAUTH_TOKEN }}

  deploy-ephemeral:
     name: Ephemeral
     uses: ./.github/workflows/deploy-ephemeral.yml
     needs: [build-and-push]
     permissions:
       contents: read
       id-token: write
       pull-requests: write
     with:
       environment: uat
       ECR_REGION: ${{vars.ECR_REGION}}
       ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
     secrets:
       ECR_REGISTRY_URL: ${{ secrets.ECR_REGISTRY_URL }}
       ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
       KUBE_CERT: ${{ secrets.KUBE_CERT }}
       KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
       KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
       KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
